In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(3, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
print(torch.rand(3, 3))

tensor([[-0.3190, -0.5383, -0.0556],
        [-0.0187, -0.8541, -0.4718],
        [-0.2155, -0.1340, -0.5237]])


In [12]:
torch.tensor([2.2, 3.3, 4.4])

tensor([2.2000, 3.3000, 4.4000])

In [20]:
x = torch.ones(3, 5, dtype=torch.int)
x

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [17]:
torch.randn_like(x, dtype=torch.float)

tensor([[-1.1313, -0.7269,  0.8860],
        [ 0.4663,  0.3816,  0.2916],
        [ 0.5026, -0.6812,  0.2697]])

In [21]:
x.size()

torch.Size([3, 5])

In [24]:
x - torch.rand(3, 5)*2

tensor([[ 0.5164, -0.3426,  0.7663, -0.5221, -0.4895],
        [ 0.2849, -0.6211, -0.0190,  0.3403,  0.6763],
        [-0.2585,  0.0471, -0.3852, -0.5428, -0.1795]])

In [25]:
torch.add(x, torch.rand(3, 5))

tensor([[1.3201, 1.7649, 1.0923, 1.2800, 1.3390],
        [1.5622, 1.9545, 1.7419, 1.1666, 1.5946],
        [1.7410, 1.8716, 1.3684, 1.6197, 1.9555]])

In [27]:
torch.empty(2, 2)

tensor([[-3.0408e+29,  4.5909e-41],
        [ 0.0000e+00,  0.0000e+00]])

In [28]:
x[1, :]

tensor([1, 1, 1, 1, 1], dtype=torch.int32)

In [30]:
x.view(1, -1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [31]:
x.view(5, 3)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [32]:
torch.rand(1).item() # take python value from tensor with size 1

0.2680565118789673

In [36]:
type(torch.zeros(2, 2))

torch.Tensor

In [37]:
type(torch.empty(2, 2))

torch.Tensor

In [38]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [40]:
type(torch.ones(2, 2).numpy())

numpy.ndarray

In [41]:
import numpy as np

In [46]:
torch.from_numpy(np.random.rand(2))

tensor([0.7206, 0.4878], dtype=torch.float64)

In [47]:
torch.cuda.is_available()

True

In [48]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 

tensor([[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]], device='cuda:0', dtype=torch.int32)
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=torch.float64)
